# Random Sampling With Numpy

In [17]:
import numpy as np
import random 

In [19]:
np.random.random(1)

array([0.90864888])

In [3]:
np.random.random((3,3))

array([[0.52371982, 0.881332  , 0.73273188],
       [0.53637369, 0.28476114, 0.2040614 ],
       [0.86482779, 0.67658336, 0.89953631]])

In [4]:
np.random.randint(1,4)

2

In [5]:
np.random.randint(1,4, (2,4,4))

array([[[3, 1, 3, 3],
        [2, 1, 1, 3],
        [3, 2, 2, 3],
        [2, 3, 3, 3]],

       [[2, 3, 2, 2],
        [1, 3, 2, 2],
        [3, 3, 2, 3],
        [3, 3, 3, 3]]])

In [6]:
np.random.seed(10)
np.random.randint(1,4, (2,4,4))

array([[[2, 2, 1, 1],
        [2, 1, 2, 2],
        [1, 2, 2, 3],
        [1, 2, 1, 3]],

       [[1, 3, 1, 1],
        [1, 3, 1, 3],
        [3, 2, 1, 1],
        [3, 2, 3, 2]]])

In [7]:
np.random.seed(10)
np.random.randint(1,4, (2,4,4))

array([[[2, 2, 1, 1],
        [2, 1, 2, 2],
        [1, 2, 2, 3],
        [1, 2, 1, 3]],

       [[1, 3, 1, 1],
        [1, 3, 1, 3],
        [3, 2, 1, 1],
        [3, 2, 3, 2]]])

In [8]:
np.random.rand(3)

array([0.13145815, 0.41366737, 0.77872881])

In [9]:
np.random.randn(3) # n can give value positive or negetive.

array([-1.25424191,  0.33157855, -0.30860049])

In [15]:
x = [1,2,3,4]
np.random.choice(x)

4

In [16]:
np.random.permutation(x)

array([4, 2, 1, 3])